import type { Matrix, MatrixCell } from '../api'
import type { Resource } from '../useResource'
import { Badge, Empty, Hash, Panel, ResourceNote } from './common'

export function cellOutcome(cell: MatrixCell) { return !cell.episode_id ? 'NOT_RUN' : ['INTERRUPTED', 'LAB_ERROR'].includes(cell.lifecycle) ? cell.lifecycle : cell.outcome ?? cell.lifecycle }
export function OutcomeMatrix({ matrix, selectedEpisode, onEpisode }: { matrix: Resource<Matrix>; selectedEpisode: string | null; onEpisode: (id: string) => void }) {
  const counts = matrix.data?.counts
  return <Panel title="Fault × policy ledger" number="04" className="matrix-panel" aside={<span className="small-label">Every trial stays visible</span>}><ResourceNote resource={matrix} />
    <div className="stat-strip">{[['completed', 'Completed'], ['violations', 'Violations'], ['safe_unresolved', 'Safe unresolved'], ['correctly_rejected', 'Correctly rejected']].map(([key, title]) => <div key={key}><strong>{counts?.[key] ?? '—'}<span> / {counts?.valid_attempted ?? '—'}</span></strong><span>{title}</span></div>)}</div>
    <p className="muted">Raw outcomes / valid attempted trials. Lab errors: {counts?.lab_errors ?? '—'} · interrupted: {counts?.interrupted ?? '—'} · scheduled: {counts?.scheduled ?? '—'} · triggered: {counts?.triggered ?? '—'} · untriggered: {counts?.untriggered ?? '—'}. No result is inferred for a trial without a verdict.</p>
    {!matrix.data?.cells.length ? <Empty>No trials yet. Create a campaign and explicitly start it to populate the ledger.</Empty> : <div className="table-scroll"><table><caption className="sr-only">Fault scenarios by policy version, including every repeated trial</caption><thead><tr><th>Scenario / episode</th><th>Arm / policy hash</th><th>Outcome</th><th>Fault</th><th>Provenance</th><th>Measured usage</th></tr></thead><tbody>{matrix.data.cells.map((cell, i) => <tr key={`${cell.episode_id}:${i}`} className={cell.episode_id === selectedEpisode ? 'selected-row' : ''}><td><strong>{cell.scenario_alias}</strong>{cell.episode_id ? <button className="text-button episode-select" onClick={() => onEpisode(cell.episode_id!)} aria-pressed={cell.episode_id === selectedEpisode}>{cell.episode_id} ↗</button> : <p>Not run</p>}</td><td><strong>{cell.arm === 'B1' ? 'B1 · handwritten reference' : cell.arm === 'B0' ? 'B0 · empty overlay' : 'L · policy enabled'}</strong><Hash value={cell.policy_hash} /></td><td><Badge value={cellOutcome(cell)} /></td><td>{cell.fault_scheduled ? cell.fault_triggered ? 'Triggered' : 'Scheduled · untriggered' : 'Healthy / no scheduled fault'}</td><td><Badge value={cell.source_mode} /><div className="muted">{cell.telemetry_provenance.replaceAll('_', ' ')}</div></td><td>{cell.usage ? <>{cell.usage.http_attempts ?? '—'} HTTP · {cell.usage.model_calls ?? '—'} model<br />{cell.usage.wall_seconds == null ? '—' : cell.usage.wall_seconds.toFixed(3)} seconds</> : 'Not recorded in projection'}</td></tr>)}</tbody></table></div>}
  </Panel>
}
