import { api } from '../api'
import type { AgentRegistration } from '../generated/contracts'
import { useResource, type Resource } from '../useResource'
import { Badge, Empty, EpisodeLinks, Field, Hash, Json, Panel, ResourceNote } from './common'
function PortabilityRecord({ id, onEpisode }: { id: string; onEpisode: (id: string) => void }) {
  const result = useResource(`portability:${id}`, () => api.portability(id))
  const p = result.data
  return <article className="experiment"><ResourceNote resource={result} />{p && <><h3>{p.portability_id}</h3><Badge value={p.provenance_class} /> <Badge value={p.status} /><dl className="facts"><Field name="Target registration">{p.target_registration_id}</Field><Field name="Policy source">{p.policy_source}</Field><Field name="Exact transferred hash"><Hash value={p.policy_hash} /></Field></dl>{p.compatibility_failures.map((f, i) => <p className="error" key={i}>{f}</p>)}{p.trial_pairs.map((pair, i) => <div className="trial-pair" key={i}>Pair {i + 1}<EpisodeLinks ids={pair} onSelect={onEpisode} /></div>)}{p.limitations.map((l, i) => <p className="muted" key={i}>{l}</p>)}<Json value={p} title="Full portability provenance" /></>}</article>
}
export function PortabilityPanel({ registrations, portabilityIds, onEpisode }: { registrations: Resource<AgentRegistration[]>; portabilityIds?: string[]; onEpisode: (id: string) => void }) {
  return <Panel title="Agent portability" number="09"><ResourceNote resource={registrations} /><p className="notice">Independent external validation is {portabilityIds?.length ? 'reported separately below.' : 'pending. Internal smoke does not satisfy this gate.'}</p>{!registrations.data?.length && <Empty>No reviewed agent registration available.</Empty>}{registrations.data?.map(r => <details className="registration" key={r.registration_id}><summary><strong>{r.name}</strong> · {r.version}<span><Badge value={r.provenance_class} /> <Badge value={r.dry_run_status} /></span></summary><dl className="facts"><Field name="Registration">{r.registration_id}</Field><Field name="Source">{r.source_origin}</Field><Field name="Owner">{r.source_owner}</Field><Field name="Revision">{r.source_revision}</Field><Field name="License / permission">{r.license} · {r.permission_ref}</Field><Field name="Source hash"><Hash value={r.source_hash} /></Field><Field name="Budget compatibility">{r.budget_compatible ? 'Compatible' : 'Incompatible'}</Field></dl>{r.limitations.map((l, i) => <p className="muted" key={i}>{l}</p>)}<Json value={r} title="Capability mapping and adapter setup provenance" /></details>)}{portabilityIds?.map(id => <PortabilityRecord key={id} id={id} onEpisode={onEpisode} />)}</Panel>
}
