import { useRef, useState } from 'react'
import { api, type ConfigStatus } from '../api'
import type { AgentRegistration, PolicyVersion, RegressionBundle, RegressionCase, RegressionExecution } from '../generated/contracts'
import { useResource } from '../useResource'
import { Badge, Empty, EpisodeLinks, Field, Hash, Json, Panel, ResourceNote } from './common'
export function RegressionControls({ cases, registrations, policies, config, replay, onEpisode }: { cases?: RegressionCase[]; registrations?: AgentRegistration[]; policies?: PolicyVersion[]; config?: ConfigStatus; replay: boolean; onEpisode: (id: string) => void }) {
  const [selected, setSelected] = useState(''); const [agent, setAgent] = useState(''); const [policy, setPolicy] = useState('')
  const [bundle, setBundle] = useState<RegressionBundle>(); const [execution, setExecution] = useState<RegressionExecution>(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const locked = useRef(false)
  const regression = cases?.find(c => c.regression_id === selected)
  const registration = registrations?.find(r => r.registration_id === agent)
  const running = useResource(execution ? `regression:${execution.execution_id}` : null, () => api.execution(execution!.execution_id))
  const latest = running.data ?? execution
  const allowedPolicies = policies?.filter(p => (p.decision === 'ACCEPTED' || p.decision === 'BASELINE') && (!bundle || p.policy_hash === bundle.policy_hash)) ?? []
  const approvedProfile = config?.execution_profiles?.find(p => p.profile_id === bundle?.execution_profile_id)
  const liveReady = !!config?.live_enabled && !!config.model_configured && !!approvedProfile
  async function loadBundle(download: boolean) {
    if (!regression || locked.current) return
    locked.current = true; setBusy(true); setError(null)
    try {
      const value = await api.bundle(regression.regression_id); setBundle(value)
      if (download) { const url = URL.createObjectURL(await api.download(regression.regression_id)); const a = document.createElement('a'); a.href = url; a.download = `${value.bundle_id}.zip`; a.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000) }
    } catch (e) { setError(e instanceof Error ? e.message : 'Bundle read failed.') } finally { locked.current = false; setBusy(false) }
  }
  return <Panel title="Portable regression" number="08"><p className="muted">Inspect and download stored evidence, or explicitly execute a new regression in fresh synthetic worlds.</p>{!cases?.length ? <Empty>No regression bundle has been exported for this campaign.</Empty> : <><label>Saved regression<select value={selected} disabled={busy} onChange={e => { setSelected(e.target.value); setBundle(undefined); setExecution(undefined); setPolicy(''); setAgent('') }}><option value="">Select a regression</option>{cases.map(c => <option value={c.regression_id} key={c.regression_id}>{c.regression_id} · {c.target_invariant}{!c.bundle_id ? ' · export pending' : ''}</option>)}</select></label><div className="controls"><button disabled={!regression?.bundle_id || busy} onClick={() => void loadBundle(false)}>Inspect saved bundle</button><button disabled={!regression?.bundle_id || busy} onClick={() => void loadBundle(true)}>Download regression</button></div></>}
    {bundle && <><dl className="facts"><Field name="Scope">{bundle.scope ?? 'orders.upgrade_then_confirm/v1'}</Field><Field name="Execution profile">{bundle.execution_profile_id}</Field><Field name="Declared per-episode budget">{bundle.caps.actor_calls ?? '—'} actor calls · {bundle.caps.http_attempts ?? '—'} HTTP attempts · {bundle.caps.wall_seconds ?? '—'} seconds</Field><Field name="Manifest"><Hash value={bundle.manifest_hash} /></Field></dl><Json value={bundle} title="Saved bundle, full repeated trials and setup instructions" /><label>Reviewed agent<select value={agent} onChange={e => setAgent(e.target.value)}><option value="">Select registered agent</option>{registrations?.map(r => <option key={r.registration_id} value={r.registration_id} disabled={r.dry_run_status !== 'PASSED' || !r.budget_compatible}>{r.name} · {r.provenance_class} · {r.dry_run_status}</option>)}</select></label><label>Immutable policy<select value={policy} onChange={e => setPolicy(e.target.value)}><option value="">Select policy version</option>{allowedPolicies.map(p => <option key={p.version} value={p.version}>{p.version} · {p.decision}</option>)}</select></label><p className="notice">Fresh execution can make bounded model and telemetry calls. It allocates new world and execution IDs. {registration?.provenance_class === 'internal_smoke' && 'This agent proves internal harness plumbing only.'}</p><button className="primary" disabled={replay || busy || !liveReady || !!config?.active_campaign_id || !registration || registration.dry_run_status !== 'PASSED' || !registration.budget_compatible || !policy || latest?.status === 'RUNNING' || latest?.status === 'PENDING'} onClick={async () => { if (!regression || locked.current) return; locked.current = true; setBusy(true); setError(null); try { setExecution(await api.execute(regression.regression_id, agent, bundle.execution_profile_id, policy)) } catch (e) { setError(e instanceof Error ? e.message : 'Execution failed.') } finally { locked.current = false; setBusy(false) } }}>Run fresh regression ↗</button>{!liveReady && <p className="muted">Fresh execution awaits configured live access.</p>}</>}
    <ResourceNote resource={running} />{latest && <article className="experiment"><h3>New execution · {latest.execution_id}</h3><Badge value={latest.mode} /> <Badge value={latest.status} /><dl className="facts"><Field name="Usage">{latest.usage.model_calls ?? 'Not recorded'} model calls · {latest.usage.http_attempts ?? 'Not recorded'} HTTP attempts</Field><Field name="Fresh worlds">{latest.world_ids.join(', ') || 'Not allocated yet'}</Field></dl><EpisodeLinks ids={latest.episode_ids} onSelect={onEpisode} />{latest.stop_reason && <p>{latest.stop_reason}</p>}<Json value={latest} title="Execution budget and provenance" /></article>}{error && <p role="alert" className="error">{error}</p>}
  </Panel>
}
