import type { Campaign, PolicyVersion } from '../generated/contracts'
import type { Matrix } from '../api'
import type { Experiments } from '../experiments'
import { Badge, Field, Panel } from './common'

// Every value below is read from persisted records. Nothing is inferred, and a stage
// that did not run is reported as not reached rather than left blank.
export function campaignProposals(policies: PolicyVersion[] | undefined, matrix: Matrix | undefined): PolicyVersion[] {
  const episodes = new Set((matrix?.cells ?? []).map(c => c.episode_id).filter((v): v is string => !!v))
  return (policies ?? []).filter(p => p.author === 'mechanic' && p.development_episode_ids.some(id => episodes.has(id)))
}

export function RunSummary({ campaign, matrix, experiments, policies }: { campaign?: Campaign; matrix?: Matrix; experiments?: Experiments; policies?: PolicyVersion[] }) {
  if (!campaign) return null
  const counts = matrix?.counts
  const records = experiments?.counterexamples ?? []
  const first = records[0]
  const counterexample = first?.counterexample
  const reduction = first?.reduction ?? null
  const diagnostics = records.flatMap(r => r.diagnostics)
  const interventions = records.flatMap(r => r.interventions)
  const challenges = records.flatMap(r => r.challenges)
  const tested = interventions.at(-1)
  const diagnosis = diagnostics.at(-1)
  const challenge = challenges.at(-1)
  const proposals = campaignProposals(policies, matrix)
  const accepted = proposals.find(p => p.decision === 'ACCEPTED')
  const verified = (experiments?.ingestions ?? []).filter(i => i.status === 'weave_verified').length
  return <Panel title="Run summary" className="summary-panel" aside={<span className="small-label">Read from persisted records</span>}>
    <div className="stat-strip">
      <div><strong>{counts?.valid_attempted ?? '—'}</strong><span>Trials recorded</span></div>
      <div><strong>{counts?.violations ?? '—'}</strong><span>Violations</span></div>
      <div><strong>{counts?.completed ?? '—'}</strong><span>Completed</span></div>
      <div><strong>{campaign.usage?.model_calls ?? '—'}</strong><span>Model calls</span></div>
      <div><strong>{verified}<span> / {experiments?.ingestions.length ?? 0}</span></strong><span>Weave verified</span></div>
    </div>
    <dl className="facts compact">
      <Field name="1 · Repeatable failure">{counterexample
        ? <><Badge value={counterexample.reproduced ? 'SUPPORTED' : 'INCONCLUSIVE'} /> {counterexample.target_violation_count ?? 'not recorded'} of {counterexample.valid_count ?? 'not recorded'} fresh trials violated {counterexample.target_invariant}</>
        : <><Badge value="NOT_RUN" /> No qualifying repeated violation was recorded.</>}</Field>
      <Field name="2 · Reduced fault">{reduction
        ? <><Badge value={reduction.status} /> {reduction.stopping_reason}</>
        : <><Badge value="NOT_RUN" /> No reduction recorded.</>}</Field>
      <Field name="3 · Tested diagnosis">{tested
        ? <><Badge value={tested.result} /> {diagnosis ? `Fixed verdict ${diagnosis.kind}, model proposed ${diagnosis.proposed_kind}.` : 'No diagnostic record.'}</>
        : <><Badge value="NOT_RUN" /> No controlled intervention finished.</>}</Field>
      <Field name="4 · Model-written repair">{proposals.length
        ? <>{proposals.length} candidate {proposals.length === 1 ? 'policy' : 'policies'} generated by the Mechanic. None was hand-written.</>
        : <><Badge value="NOT_RUN" /> No candidate policy was generated in this campaign.</>}</Field>
      <Field name="5 · Adversarial challenge">{challenge
        ? <><Badge value={challenge.status} /> {challenge.stopping_reason}</>
        : <><Badge value="NOT_RUN" /> Not reached. A candidate must repair every source-validation pair first.</>}</Field>
      <Field name="6 · Promotion">{accepted
        ? <><Badge value="ACCEPTED" /> {accepted.version} is the active learned policy.</>
        : <><Badge value="NOT_RUN" /> No promotion batch qualified.</>}</Field>
    </dl>
    <p className="notice">{accepted
      ? `A learned policy was accepted; the active version is ${campaign.active_policy_version ?? accepted.version}.`
      : `No recovery policy has been accepted in this campaign. The active policy is still ${campaign.active_policy_version ?? 'the baseline'}, and every rejected candidate is retained above.`}</p>
    {campaign.terminal_reason && <p className="muted">Recorded outcome · {campaign.terminal_reason}</p>}
  </Panel>
}
