import { useState } from 'react'
import { api, type ConfigStatus } from '../api'
import type { AriaAnalysis, Campaign } from '../generated/contracts'
import type { Experiments } from '../experiments'
import type { Resource } from '../useResource'
import { Badge, Empty, EvidenceLink, Field, Json, Panel, ResourceNote } from './common'
import { AriaEvidenceForm } from './AriaEvidenceForm'
export function SponsorEvidence({ config, campaign, experiments, aria, replay }: { config?: ConfigStatus; campaign?: Campaign; experiments?: Experiments; aria: Resource<AriaAnalysis[]>; replay: boolean }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null)
  return <Panel title="Sponsor evidence" number="10"><div className="sponsor-block"><div className="split-heading"><h3>Weave</h3><Badge value={campaign?.telemetry_status ?? config?.sponsor.weave ?? 'PENDING'} /></div><p className="muted">Local recording, upload status and verified remote readback are separate states.</p>{!experiments?.evidence.length && <Empty>No retrieved Weave references recorded.</Empty>}{experiments?.evidence.map(e => <div className="evidence-reference" key={e.episode_id}><Badge value={e.source} /><dl className="facts"><Field name="Episode"><code>{e.episode_id}</code></Field><Field name="Root call"><code>{e.root_call_id ?? 'Not recorded'}</code></Field><Field name="Project">{e.source_project ?? 'Local only'}</Field></dl><EvidenceLink url={e.root_call_url ?? e.trace_url}>Open Weave trace</EvidenceLink></div>)}{experiments?.ingestions.map(i => <div className="evidence-reference" key={i.episode_id}><strong>Ingestion · {i.state}</strong><code>{i.episode_id}</code>{i.error_code && <p>{i.error_code}</p>}<Json value={i} title="Ingestion progress" /></div>)}<button disabled={!campaign || replay || busy} onClick={async () => { if (!campaign || busy) return; setBusy(true); try { await api.retry(campaign.campaign_id); setMessage('Retry accepted for stored evidence only.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Retry failed.') } finally { setBusy(false) } }}>Retry evidence sync</button>{message && <p role="status" className="muted">{message}</p>}</div><div className="sponsor-block"><div className="split-heading"><h3>Aria analyst</h3><Badge value={campaign?.aria_status ?? config?.sponsor.aria ?? 'PENDING'} /></div><ResourceNote resource={aria} /><p className="muted">Advisory analysis. Aria cannot change the fixed scorer or promote a policy.</p>{!aria.data?.length && <Empty>No attributed Aria output recorded. Required sponsor acceptance remains pending.</Empty>}{aria.data?.map(a => <article className="evidence-reference" key={a.analysis_id}><Badge value={a.status} /><p><strong>{a.invocation_mode === 'automatic' ? 'Automatic invocation · manual UI capture' : 'Manual chat fallback · manual UI capture'}</strong></p><p>{a.summary}</p><p className="muted">Recorded by {a.recorder} · {new Date(a.observed_at).toLocaleString()}. A pasted pointer is not independent remote verification.</p><div className="controls"><EvidenceLink url={a.history_url}>Automation history</EvidenceLink><EvidenceLink url={a.output_url}>Aria output</EvidenceLink></div><Json value={a} title="Source references and invocation provenance" /></article>)}{campaign && <AriaEvidenceForm campaignId={campaign.campaign_id} disabled={replay} />}</div></Panel>
}
