import type { Episode, Event } from '../generated/contracts'
import type { Resource } from '../useResource'
import { Badge, Empty, Field, Hash, Json, Panel, ResourceNote, label } from './common'

export function Timeline({ episode, events }: { episode: Resource<Episode>; events: Resource<Event[]> }) {
  const value = episode.data
  return <Panel title="Evidence timeline" number="02" className="timeline-panel" aside={<span className="small-label">Sequence is authority</span>}>
    <ResourceNote resource={episode} /><ResourceNote resource={events} />
    {!value && !episode.loading && <Empty>Select a recorded trial below. Its original observations, report and fixed verdict appear here.</Empty>}
    {value && <><div className="episode-heading"><code>{value.episode_id}</code><Badge value={value.source_mode} /></div><dl className="facts compact"><Field name="World"><code>{value.world_id}</code></Field><Field name="Trial">{value.trial_index} · {value.arm} · {label(value.experiment_purpose)}</Field><Field name="Policy">{value.policy_version} <Hash value={value.policy_hash} /></Field></dl>
      <div className="timeline-scroll"><ol className="timeline">{events.data?.map(event => <li key={event.seq}><span className="sequence">{String(event.seq).padStart(2, '0')}</span><div className="event-body"><div className="event-title"><strong>{label(event.type)}</strong><span>{event.role} · t{event.tick}</span></div>{event.at && <time dateTime={event.at}>{new Date(event.at).toLocaleTimeString()}</time>}{event.evidence_id && <code className="event-ref">{event.evidence_id}</code>}{event.call_id && <code className="event-ref">{event.call_id}</code>}<Json value={event.payload ?? {}} title="Observation / event payload" /></div></li>)}</ol>{!events.data?.length && <Empty>No visible events recorded yet.</Empty>}</div>
      <div className="verdict"><div className="split-heading"><h3>Fixed Referee verdict</h3><Badge value={value.verdict?.outcome ?? value.lifecycle ?? 'NOT_RUN'} /></div>{value.split !== 'development' && <p className="muted">Protected evaluation details are withheld by the backend.</p>}{value.verdict ? <><dl className="facts compact"><Field name="Upgrade effects">{value.verdict.upgrade_effects}</Field><Field name="Notification effects">{value.verdict.notification_effects}</Field><Field name="Decision / horizon">{value.verdict.decision_tick} / {value.verdict.horizon_tick} ticks</Field></dl><div className="checks">{value.verdict.checks.map(c => <span className={c.passed ? 'check-pass' : 'check-fail'} key={c.check_id} title={c.category}>{c.check_id} {c.passed ? 'Pass' : 'Fail'}</span>)}</div><Json value={value.verdict} title="Full fixed verdict and evidence IDs" /></> : <p className="muted">No scored outcome available.</p>}{value.report && <><h3>Original actor report</h3><dl className="facts compact"><Field name="Upgrade">{value.report.upgrade_outcome === 'PENDING' ? 'Last observed pending; outcome remains unresolved' : value.report.upgrade_outcome}</Field><Field name="Notification">{value.report.notification_outcome === 'PENDING' ? 'Last observed pending; outcome remains unresolved' : value.report.notification_outcome}</Field></dl><Json value={value.report} title="Unaltered report and next action" /></>}{value.reason && <p className="error">{value.reason}</p>}</div>
    </>}
  </Panel>
}
