import type { Campaign, Episode, Event, PolicyVersion } from '../src/generated/contracts'
import type { ConfigStatus, Matrix } from '../src/api'
export const hash = 'a'.repeat(64)
export const config: ConfigStatus = { schema_version: 'faultlab/v1', model: 'not-configured', model_configured: false, live_enabled: false, profile_ids: ['offline-v1', 'live-v1'], sponsor: { weave: 'PENDING', aria: 'PENDING' }, active_campaign_id: null }
export const campaign: Campaign = { schema_version: 'faultlab/v1', campaign_id: 'campaign-fixture', mode: 'baseline', state: 'COMPLETED', state_seq: 3, task_text: 'Upgrade the synthetic order and confirm.', order_id: 'order-fixture', config_profile_id: 'offline-v1', model: 'deterministic-reference/internal-smoke', configuration_hash: hash, active_policy_version: 'policy-v0', latest_episode_id: 'episode-fixture', stop_requested: false, caps: { model_calls: 100, tokens: 100000, dollars: 10 }, usage: { model_calls: 0, http_attempts: 4, cost_dollars: null }, reserved_calls: 0, telemetry_status: 'local_recorded', aria_status: 'PENDING', created_at: '2026-09-12T12:00:00Z', updated_at: '2026-09-12T12:00:01Z' }
export const episode: Episode = { schema_version: 'faultlab/v1', campaign_id: campaign.campaign_id, episode_id: 'episode-fixture', origin: 'faultlab_evaluation', split: 'development', arm: 'B1', source_mode: 'offline_fixture', experiment_purpose: 'discovery', trial_index: 1, study_id: 'study-fixture', evidence_context_id: 'context-fixture', execution_epoch: 0, world_id: 'world-fixture', task_id: 'task-fixture', scenario_hash: hash, policy_hash: hash, policy_version: 'policy-v0', model: 'deterministic-reference/internal-smoke', configuration_hash: hash, lifecycle: 'COMPLETED', report: { upgrade_outcome: 'SUCCEEDED', notification_outcome: 'SUCCEEDED', overall: 'COMPLETED', evidence_ids: ['evidence-fixture'], next_action: { kind: 'NONE' } }, verdict: { verdict_id: 'verdict-fixture', episode_id: 'episode-fixture', outcome: 'COMPLETED', checks: Array.from({ length: 8 }, (_, i) => ({ check_id: `C${i + 1}` as 'C1', passed: true, category: 'fixture-only' })), evidence_ids: ['evidence-fixture'], supported_completion: true, useful_resolution: 'completed', fault_executions: [], upgrade_effects: 1, notification_effects: 1, decision_tick: 4, horizon_tick: 25, scorer_hash: hash }, usage: { http_attempts: 4, model_calls: 0 }, started_at: '2026-09-12T12:00:00Z', ended_at: '2026-09-12T12:00:01Z' }
export const events: Event[] = [ { episode_id: 'episode-fixture', seq: 1, tick: 0, at: '2026-09-12T12:00:00Z', role: 'coordinator', type: 'episode_started', payload: { world_id: 'world-fixture' }, visibility: 'PUBLIC_OBSERVATION' }, { episode_id: 'episode-fixture', seq: 3, tick: 1, at: '2026-09-12T12:00:00Z', role: 'actor', type: 'observation_delivered', payload: { observed_version: 2 }, evidence_id: 'evidence-fixture', visibility: 'PUBLIC_OBSERVATION' } ]
export const baseline: PolicyVersion = { version: 'policy-v0', parent_version: null, content: { parent_version: 'policy-v0', rules: [] }, policy_hash: hash, author: 'baseline', raw_proposal_ref: null, development_episode_ids: [], decision: 'BASELINE', created_at: '2026-09-12T12:00:00Z' }
export const matrix: Matrix = { campaign_id: campaign.campaign_id, cells: [{ episode_id: episode.episode_id, scenario_alias: hash.slice(0, 10), arm: 'B1', policy_hash: hash, outcome: 'COMPLETED', lifecycle: 'COMPLETED', fault_scheduled: false, fault_triggered: false, source_mode: 'offline_fixture', telemetry_provenance: 'local_only', usage: episode.usage }], counts: { valid_attempted: 1, completed: 1, violations: 0, safe_unresolved: 0, correctly_rejected: 0, lab_errors: 0, interrupted: 0, scheduled: 0, triggered: 0, untriggered: 0 } }
export const experiments = { counterexamples: [], evidence: [], ingestions: [], portability_ids: [] }
export function fixtureResponse(url: string, currentCampaign: Campaign = campaign): unknown {
  if (url.endsWith('/health')) return { status: 'ok', service: 'faultlab-backend' }
  if (url.endsWith('/config/status')) return config
  if (url.endsWith('/policies')) return [baseline]
  if (url.endsWith('/agent-registrations')) return []
  if (url.includes('/events?')) { const after = Number(new URL(url, 'http://local').searchParams.get('after')); return { events: events.filter(e => e.seq > after), next_after: Math.max(after, 3), has_more: false } }
  if (url.includes('/episodes/')) return episode
  if (url.endsWith('/matrix')) return matrix
  if (url.endsWith('/experiments')) return experiments
  if (url.endsWith('/aria-evidence') || url.endsWith('/regressions')) return []
  if (url.includes('/campaigns/')) return currentCampaign
  throw new Error(`Unexpected fixture request: ${url}`)
}

export const testedExperiment = {
  counterexample: { counterexample_id: 'counter-fixture', campaign_id: campaign.campaign_id, agent_registration_id: 'reference-fixture', source_episode_id: episode.episode_id, target_invariant: 'C1', scenario_hash: hash, configuration_hash: hash, report_ref: null, verdict_ref: 'verdict-fixture', reproduction_trial_ids: ['episode-r1', 'episode-r2', 'episode-r3'], target_violation_count: 3, valid_count: 3, attempted_count: 3, reproduced: true },
  source_recipe: { seed: 0, primitives: [{ kind: 'F1', target_tool: 'update_order', target_service: 'orders', occurrence: 1, parameters: { response_delay_ms: 1500 } }] },
  retained_recipe: null,
  reduction: { counterexample_id: 'counter-fixture', reducer_hash: hash, reduction_order: ['remove_primitive'], original_recipe_hash: hash, retained_recipe_hash: null, attempts: [{ transform: 'remove_primitive', parent_hash: hash, child_hash: 'b'.repeat(64), trial_ids: ['episode-reduce1', 'episode-reduce2', 'episode-reduce3'], retained: false, reason: 'Target invariant no longer violated.' }], status: 'INCOMPLETE', valid_count: 3, attempted_count: 3, target_violation_count: 3, stopping_reason: 'Reduction budget reached.', neighborhood_exhausted: false },
  diagnostics: [{ diagnostic_id: 'diagnostic-fixture', counterexample_id: 'counter-fixture', proposed_kind: 'POLICY_GAP', kind: 'INCONCLUSIVE', explanation: 'Recorded evidence does not isolate a repair.', intervention_ids: ['intervention-fixture'], reproduction_ids: ['episode-r1', 'episode-r2', 'episode-r3'], evidence_ids: ['evidence-fixture'], authority_paths: ['get_operation_status'], equivalence_refs: [], tested_scope: 'This contract and a 20-tick actor deadline.', required_behavior: 'Retain uncertainty when a terminal receipt is unavailable.', limitations: ['No universal impossibility claim.'], checker_hash: hash, protocol_hash: hash }],
  interventions: [{ intervention_id: 'intervention-fixture', counterexample_id: 'counter-fixture', hypothesis: 'The original operation status resolves the timeout.', proposal_ref: 'proposal-fixture', change: 'Test original-operation status recovery.', control_hash: hash, treatment_hash: 'b'.repeat(64), trial_pairs: [['episode-control1', 'episode-treatment1']], result: 'INCONCLUSIVE', evidence_ids: ['evidence-fixture'], limitations: ['Only one of three requested pairs finished.'] }],
  challenges: [{ challenge_id: 'challenge-fixture', candidate_hash: 'b'.repeat(64), incumbent_hash: hash, source_validation_ref: 'validation-fixture', schedule_hashes: [hash, 'b'.repeat(64), 'c'.repeat(64), 'd'.repeat(64)], selection_refs: ['selection-fixture'], novel_schedule_hashes: ['d'.repeat(64)], trial_pairs: [['episode-incumbent1', 'episode-candidate1']], failed_checks: ['C1'], status: 'COUNTEREXAMPLE_FOUND', stopping_reason: 'Candidate violated C1; saved counterexample returns to development.' }],
}

export const regressionCase = { regression_id: 'regression-fixture', campaign_id: campaign.campaign_id, counterexample_id: 'counter-fixture', target_invariant: 'C1', first_failing_policy: 'policy-v0', accepted_policy: 'policy-v0', reduction_ref: null, diagnostic_ref: null, challenge_ref: null, bundle_id: 'bundle-fixture' } as const
export const bundle = { fixture_id: 'standard-v1', export_version: 'faultlab-regression/v1', bundle_id: 'bundle-fixture', manifest_hash: hash, files: [{ path: 'policy.json', sha256: hash, size_bytes: 12 }], harness_version: 'faultlab-runner-v1', harness_hash: hash, source_recipe: { seed: 0, primitives: [] }, retained_recipe: null, scope: 'orders.upgrade_then_confirm/v1', contract_hash: hash, capability_hash: hash, configuration_hash: hash, scorer_hash: hash, interpreter_hash: hash, policy_hash: hash, schema_hash: hash, dependency_lock_hash: hash, target_invariant: 'C1', source_refs: ['episode-fixture'], trial_results: [], registration_requirements: ['Reviewed local registration'], execution_profile_id: 'sandbox-v1', caps: { actor_calls: 8, http_attempts: 18, wall_seconds: 90 }, setup_instructions: 'Fixture for UI contract tests only.' }
export const registration = { registration_id: 'agent-fixture', name: 'Internal fixture', version: '1', provenance_class: 'internal_smoke', source_origin: 'local fixture', source_owner: 'FaultLab tests', source_revision: 'fixture-v1', source_hash: hash, license: 'test only', permission_ref: 'fixture-permission', adapter_entrypoint_id: 'fixture-adapter', adapter_hash: hash, contract_hash: hash, capability_hash: hash, reset_profile_id: 'standard-v1', oracle_hash: hash, policy_hooks: ['after_upgrade_response', 'before_confirmation', 'after_notification_response', 'before_final_report'], model: 'fixture-model', prompt_hash: hash, configuration_hash: hash, dependency_lock_hash: hash, budget_compatible: true, dry_run_status: 'PASSED', limitations: ['Internal smoke does not satisfy external validation.'] }
