// Generated by scripts/export-wire-types.py from contracts/*.schema.json.
// JSON wire data only; validate responses before using them.

export type AgentRegistration = {
  "schema_version"?: "faultlab/v1";
  "registration_id": string;
  "name": string;
  "version": string;
  "provenance_class": "reference" | "internal_smoke" | "external";
  "source_origin": string;
  "source_owner": string;
  "source_revision": string;
  "source_hash": string;
  "license": string;
  "permission_ref": string;
  "adapter_entrypoint_id": string;
  "adapter_hash": string;
  "contract_hash": string;
  "capability_hash": string;
  "reset_profile_id": string;
  "oracle_hash": string;
  "policy_hooks": Array<"after_upgrade_response" | "before_confirmation" | "after_notification_response" | "before_final_report">;
  "model": string;
  "prompt_hash": string;
  "configuration_hash": string;
  "dependency_lock_hash": string;
  "budget_compatible": boolean;
  "dry_run_status": "PENDING" | "PASSED" | "UNSUPPORTED";
  "limitations": Array<string>;
};

export type AriaAnalysis = {
  "schema_version"?: "faultlab/v1";
  "analysis_id": string;
  "campaign_id": string;
  "run_id": string;
  "automation_id": string;
  "invocation_mode": "automatic" | "manual";
  "provenance": "manual_ui_capture";
  "status": "PENDING" | "UNVERIFIED" | "COMPLETED" | "FAILED";
  "execution_id": (string | null);
  "observed_at": string;
  "thread_id": (string | null);
  "history_url": (string | null);
  "output_url": (string | null);
  "summary": string;
  "recorder": string;
  "verified_source_refs": Array<string>;
};

export type Campaign = {
  "schema_version"?: "faultlab/v1";
  "campaign_id": string;
  "mode": "baseline" | "learn" | "compare";
  "state"?: "IDLE" | "SELECTING" | "RUNNING" | "SCORING" | "NO_CHANGE" | "DIAGNOSING" | "REPRODUCING" | "REDUCING" | "INTERVENING" | "CANDIDATE_VALIDATION" | "CHALLENGING" | "EVALUATING" | "PROMOTED" | "REJECTED" | "WAITING_EVIDENCE" | "STOPPED" | "COMPLETED" | "ERROR";
  "state_seq"?: number;
  "execution_epoch"?: number;
  "task_text": string;
  "order_id": string;
  "config_profile_id": string;
  "model": string;
  "configuration_hash": string;
  "active_policy_version"?: string;
  "latest_episode_id"?: (string | null);
  "stop_requested"?: boolean;
  "caps"?: CampaignBudget;
  "usage"?: Usage;
  "reserved_calls"?: number;
  "telemetry_status"?: "local_recorded" | "weave_pending" | "weave_verified" | "weave_error";
  "aria_status"?: "PENDING" | "UNVERIFIED" | "COMPLETED" | "FAILED";
  "terminal_reason"?: (string | null);
  "created_at"?: string;
  "updated_at"?: string;
};

export type CampaignBudget = {
  "model_calls"?: number;
  "tokens"?: number;
  "dollars"?: number;
  "discovery_selections"?: number;
  "candidates"?: number;
  "input_tokens_per_call"?: number;
  "output_tokens_per_call"?: number;
};

export type CampaignRequest = {
  "task_text": string;
  "order_id": string;
  "mode": "baseline" | "learn" | "compare";
  "config_profile_id"?: string;
};

export type CandidatePolicy = {
  "scope"?: "orders.upgrade_then_confirm/v1";
  "parent_version": string;
  "rules": Array<PolicyRule>;
};

export type ChallengeResult = {
  "schema_version"?: "faultlab/v1";
  "challenge_id": string;
  "candidate_hash": string;
  "incumbent_hash": string;
  "source_validation_ref": string;
  "schedule_hashes": Array<string>;
  "selection_refs": Array<string>;
  "novel_schedule_hashes": Array<string>;
  "trial_pairs": Array<[string, string]>;
  "failed_checks": Array<"C1" | "C2" | "C3" | "C4" | "C5" | "C6" | "C7" | "C8">;
  "status": "PASSED_OBSERVED" | "COUNTEREXAMPLE_FOUND" | "INCONCLUSIVE" | "NOT_RUN";
  "stopping_reason": string;
};

export type CheckNextAction = {
  "kind": "CHECK_EXISTING_UPGRADE" | "CHECK_EXISTING_NOTIFICATION";
  "operation_id": string;
};

export type CheckResult = {
  "check_id": "C1" | "C2" | "C3" | "C4" | "C5" | "C6" | "C7" | "C8";
  "passed": boolean;
  "category": string;
  "evidence_ids"?: Array<string>;
  "event_ids"?: Array<string>;
};

export type Counterexample = {
  "schema_version"?: "faultlab/v1";
  "counterexample_id": string;
  "campaign_id": string;
  "agent_registration_id": string;
  "source_episode_id": string;
  "target_invariant": "C1" | "C2" | "C3" | "C4" | "C5" | "C6" | "C7" | "C8";
  "scenario_hash": string;
  "configuration_hash": string;
  "report_ref": (string | null);
  "verdict_ref": string;
  "created_at"?: string;
  "reproduction_trial_ids"?: Array<string>;
  "target_violation_count"?: number;
  "valid_count"?: number;
  "attempted_count"?: number;
  "reproduced"?: boolean;
};

export type DiagnosticProfile = {
  "schema_version"?: "faultlab/v1";
  "profile_id": "evidence_gap_v1";
  "contract_hash": string;
  "capability_hash": string;
  "oracle_hash": string;
  "fixture_hash": string;
  "normalization_hash": string;
  "probe_set": Array<string>;
  "horizon": number;
  "excluded_from_learning"?: true;
};

export type DiagnosticProposal = {
  "proposed_kind": "POLICY_GAP" | "CONTRACT_EVIDENCE_GAP" | "INCONCLUSIVE";
  "hypothesis": string;
  "evidence_ids": Array<string>;
  "requested_intervention_id": (string | null);
};

export type DiagnosticResult = {
  "schema_version"?: "faultlab/v1";
  "diagnostic_id": string;
  "counterexample_id"?: (string | null);
  "diagnostic_profile_id"?: ("evidence_gap_v1" | null);
  "proposed_kind": "POLICY_GAP" | "CONTRACT_EVIDENCE_GAP" | "INCONCLUSIVE";
  "kind": "POLICY_GAP" | "CONTRACT_EVIDENCE_GAP" | "INCONCLUSIVE";
  "explanation": string;
  "intervention_ids": Array<string>;
  "reproduction_ids": Array<string>;
  "evidence_ids": Array<string>;
  "authority_paths": Array<string>;
  "equivalence_refs": Array<string>;
  "tested_scope": string;
  "required_behavior": string;
  "limitations": Array<string>;
  "checker_hash": string;
  "protocol_hash": string;
};

export type EmptyArguments = Record<string, never>;

export type Episode = {
  "schema_version"?: "faultlab/v1";
  "campaign_id": string;
  "episode_id": string;
  "origin": "prototype" | "faultlab_evaluation";
  "split": "development" | "promotion" | "final_audit";
  "arm": "B0" | "B1" | "L";
  "source_mode": "live" | "replay" | "offline_fixture";
  "experiment_purpose": "discovery" | "reproduction" | "reduction" | "intervention" | "source_validation" | "challenge" | "promotion" | "final_audit" | "portability" | "selection_comparison" | "diagnostic_profile";
  "trial_index": number;
  "study_id": string;
  "evidence_context_id": string;
  "selector_id"?: ("explorer" | "systematic" | "random" | null);
  "execution_epoch": number;
  "agent_registration_id"?: string;
  "parent_experiment_id"?: (string | null);
  "world_id": string;
  "task_id": string;
  "scenario_hash": string;
  "policy_hash": string;
  "policy_version": string;
  "model": string;
  "configuration_hash": string;
  "lifecycle"?: "CREATED" | "RUNNING" | "SCORING" | "COMPLETED" | "INTERRUPTED" | "LAB_ERROR";
  "report"?: (TaskReport | null);
  "verdict"?: (Verdict | null);
  "usage"?: Usage;
  "started_at"?: (string | null);
  "ended_at"?: (string | null);
  "reason"?: (string | null);
};

export type EpisodeBudget = {
  "http_attempts"?: number;
  "actor_calls"?: number;
  "wait_cycles"?: number;
  "ticks"?: number;
  "policy_steps"?: number;
  "wall_seconds"?: number;
};

export type EvaluationBatch = {
  "schema_version"?: "faultlab/v1";
  "batch_id": string;
  "purpose": "discovery" | "reproduction" | "reduction" | "intervention" | "source_validation" | "challenge" | "promotion" | "final_audit" | "portability" | "selection_comparison" | "diagnostic_profile";
  "split": "development" | "promotion" | "final_audit";
  "candidate_hash": string;
  "incumbent_hash": string;
  "manifest_hash": string;
  "scorer_hash": string;
  "contract_hash": string;
  "model_hash": string;
  "trial_pairs": Array<[string, string]>;
  "trials": Array<TrialResult>;
  "usage": Usage;
  "decision": "ACCEPTED" | "REJECTED" | "NO_CHANGE" | "INCOMPLETE";
  "reason": string;
};

export type Event = {
  "schema_version"?: "faultlab/v1";
  "episode_id": string;
  "seq": number;
  "tick": number;
  "at"?: string;
  "role": "actor" | "policy" | "explorer" | "mechanic" | "referee" | "coordinator" | "telemetry";
  "type": string;
  "payload"?: Record<string, unknown>;
  "call_id"?: (string | null);
  "evidence_id"?: (string | null);
  "visibility": "PUBLIC_OBSERVATION" | "DEVELOPMENT_DIAGNOSTIC" | "PRIVATE_EVALUATOR";
};

export type EvidenceBundle = {
  "schema_version"?: "faultlab/v1";
  "episode_id": string;
  "policy_hash": string;
  "contract_hash": string;
  "scorer_hash": string;
  "source": "weave_verified" | "local_only";
  "root_call_id": (string | null);
  "child_call_ids": Array<string>;
  "observations": Array<PublicObservation>;
  "report": (TaskReport | null);
  "findings": Array<CheckResult>;
  "retrieved_at": (string | null);
  "digest": string;
  "source_project": (string | null);
};

export type ExplorerOutput = {
  "fault_spec": FaultSpec;
  "hypothesis": string;
};

export type F1 = {
  "target_tool": "update_order" | "send_confirmation";
  "target_service": "orders" | "notifications";
  "occurrence": number;
  "kind": "F1";
  "parameters": F1Parameters;
};

export type F1Parameters = {
  "response_delay_ms": number;
};

export type F2 = {
  "target_tool": "update_order";
  "target_service": "orders";
  "occurrence": number;
  "kind": "F2";
  "parameters": F2Parameters;
};

export type F2Parameters = {
  "completion_delay_ticks": number;
  "terminal_status": "SUCCEEDED" | "FAILED";
  "failure_code": ("UPGRADE_REJECTED" | null);
};

export type F3 = {
  "target_tool": "get_order";
  "target_service": "orders";
  "occurrence": number;
  "kind": "F3";
  "parameters": F3Parameters;
};

export type F3Parameters = {
  "versions_back": number;
};

export type F4 = {
  "target_tool": "get_order" | "update_order" | "get_operation_status" | "send_confirmation";
  "target_service": "orders" | "notifications";
  "occurrence": number;
  "kind": "F4";
  "parameters": F4Parameters;
};

export type F4Parameters = {
  "failure_count": number;
};

export type FaultExecution = {
  "fault_id": string;
  "scheduled"?: boolean;
  "triggered"?: boolean;
  "trigger_tick"?: (number | null);
  "call_id"?: (string | null);
  "attempt_id"?: (string | null);
  "reason"?: (string | null);
};

export type FaultSpec = {
  "schema_version"?: "faultlab/v1";
  "scope"?: "orders.upgrade_then_confirm/v1";
  "seed": number;
  "primitives": Array<(F1 | F2 | F3 | F4)>;
};

export type FileEntry = {
  "path": string;
  "sha256": string;
  "size_bytes": number;
};

export type GetOrderAction = {
  "kind"?: "tool";
  "tool": "get_order";
  "arguments": EmptyArguments;
};

export type GetStatusAction = {
  "kind"?: "tool";
  "tool": "get_operation_status";
  "arguments": StatusArguments;
};

export type IdempotencyRecord = {
  "schema_version"?: "faultlab/v1";
  "service": "orders" | "notifications";
  "key": string;
  "payload_hash": string;
  "operation_id": string;
};

export type InterventionExperiment = {
  "schema_version"?: "faultlab/v1";
  "intervention_id": string;
  "counterexample_id": string;
  "hypothesis": string;
  "proposal_ref": string;
  "change": string;
  "control_hash": string;
  "treatment_hash": string;
  "trial_pairs": Array<[string, string]>;
  "result": "SUPPORTED" | "CONTRADICTED" | "INCONCLUSIVE";
  "evidence_ids": Array<string>;
  "limitations": Array<string>;
};

export type MechanicCandidate = {
  "candidate": CandidatePolicy;
  "explanation": string;
};

export type MechanicNoChange = {
  "no_change_reason": string;
};

export type NoArgStep = {
  "op": "read_current_operation" | "read_notification_operation" | "read_order" | "defer_unresolved";
  "only_if"?: "always" | "upgrade_receipt_missing" | "notification_receipt_missing" | "current_operation_pending" | "notification_operation_pending" | "upgrade_outcome_uncertain" | "notification_outcome_uncertain" | "upgrade_terminal_failure" | "notification_terminal_failure" | "upgrade_succeeded" | "notification_succeeded" | "receipt_missing";
};

export type NoNextAction = {
  "kind": "NONE" | "ESCALATE";
};

export type NotificationEffect = {
  "schema_version"?: "faultlab/v1";
  "notification_id": string;
  "order_id": string;
  "upgrade_operation_id": string;
  "operation_id": string;
  "idempotency_key": string;
  "payload_hash": string;
  "created_tick": number;
  "template_version"?: "confirmation/v1";
};

export type Operation = {
  "schema_version"?: "faultlab/v1";
  "operation_id": string;
  "service": "orders" | "notifications";
  "task_id": string;
  "order_id": string;
  "payload_hash": string;
  "state": "PENDING" | "SUCCEEDED" | "FAILED";
  "accepted_tick": number;
  "terminal_tick"?: (number | null);
  "receipt"?: (Receipt | null);
};

export type OperationData = {
  "operation_id": string;
  "service": "orders" | "notifications";
  "order_id": string;
  "intent_hash": string;
  "status": "PENDING" | "SUCCEEDED" | "FAILED" | "UNKNOWN";
  "receipt"?: (Receipt | null);
};

export type OperationJournal = {
  "schema_version"?: "faultlab/v1";
  "episode_id": string;
  "operation_id": string;
  "service": "orders" | "notifications";
  "intent_hash": string;
  "payload_hash": string;
  "original_request": string;
  "attempt_ids": Array<string>;
  "latest_status": ("PENDING" | "SUCCEEDED" | "FAILED" | "UNKNOWN" | null);
  "terminal_receipt_id": (string | null);
};

export type Order = {
  "order_id": string;
  "applied_shipping": "standard" | "express";
  "requested_shipping": "standard" | "express";
  "version": number;
  "last_upgrade_operation_id"?: (string | null);
};

export type PolicyRule = {
  "hook": "after_upgrade_response" | "before_confirmation" | "after_notification_response" | "before_final_report";
  "when": "always" | "upgrade_receipt_missing" | "notification_receipt_missing" | "current_operation_pending" | "notification_operation_pending" | "upgrade_outcome_uncertain" | "notification_outcome_uncertain" | "upgrade_terminal_failure" | "notification_terminal_failure" | "upgrade_succeeded" | "notification_succeeded" | "receipt_missing";
  "steps": Array<(NoArgStep | WaitStep | ServiceStep | ReceiptStep)>;
};

export type PolicyVersion = {
  "schema_version"?: "faultlab/v1";
  "version": string;
  "parent_version": (string | null);
  "content": (RecoveryPolicy | null);
  "policy_hash": (string | null);
  "author": "mechanic" | "manual" | "baseline";
  "raw_proposal_ref": (string | null);
  "development_episode_ids": Array<string>;
  "decision": "BASELINE" | "PROPOSED" | "ACCEPTED" | "REJECTED" | "NO_CHANGE" | "INCOMPLETE";
  "decision_ref"?: (string | null);
  "evaluation_refs"?: Array<string>;
  "created_at"?: string;
};

export type PortabilityResult = {
  "schema_version"?: "faultlab/v1";
  "portability_id": string;
  "source_registration_id": string;
  "target_registration_id": string;
  "provenance_class": "external" | "internal_smoke";
  "policy_source": "transferred_unchanged" | "new_target_campaign";
  "policy_hash": string;
  "manifest_hash": string;
  "target_configuration_hash": string;
  "trial_pairs": Array<[string, string]>;
  "compatibility_failures": Array<string>;
  "status": "PENDING" | "COMPLETED" | "INCOMPLETE" | "UNSUPPORTED";
  "limitations": Array<string>;
};

export type PrimitiveBase = {
  "target_tool": "get_order" | "update_order" | "get_operation_status" | "send_confirmation";
  "target_service": "orders" | "notifications";
  "occurrence": number;
};

export type Provenance = {
  "schema_version"?: "faultlab/v1";
  "campaign_id": string;
  "episode_id": string;
  "origin": "prototype" | "faultlab_evaluation";
  "split": "development" | "promotion" | "final_audit";
  "arm": "B0" | "B1" | "L";
  "source_mode": "live" | "replay" | "offline_fixture";
  "experiment_purpose": "discovery" | "reproduction" | "reduction" | "intervention" | "source_validation" | "challenge" | "promotion" | "final_audit" | "portability" | "selection_comparison" | "diagnostic_profile";
  "trial_index": number;
  "study_id": string;
  "evidence_context_id": string;
  "selector_id"?: ("explorer" | "systematic" | "random" | null);
  "execution_epoch": number;
  "agent_registration_id"?: string;
  "parent_experiment_id"?: (string | null);
};

export type PublicObservation = {
  "schema_version"?: "faultlab/v1";
  "evidence_id": string;
  "episode_id": string;
  "call_id": string;
  "delivered_tick": number;
  "result": ToolResult;
  "observed_operation_id"?: (string | null);
  "observed_order_id"?: (string | null);
  "observed_intent_hash"?: (string | null);
  "source_receipt_id"?: (string | null);
};

export type Receipt = {
  "receipt_id": string;
  "operation_id": string;
  "service": "orders" | "notifications";
  "order_id": string;
  "intent_hash": string;
  "status": "SUCCEEDED" | "FAILED";
  "terminal_tick": number;
  "committed_version"?: (number | null);
  "effect_id"?: (string | null);
  "failure_code"?: ("UPGRADE_REJECTED" | "VERSION_CONFLICT" | null);
};

export type ReceiptStep = {
  "op": "require_receipt";
  "service": "orders" | "notifications";
  "status": "SUCCEEDED";
  "only_if"?: "always" | "upgrade_receipt_missing" | "notification_receipt_missing" | "current_operation_pending" | "notification_operation_pending" | "upgrade_outcome_uncertain" | "notification_outcome_uncertain" | "upgrade_terminal_failure" | "notification_terminal_failure" | "upgrade_succeeded" | "notification_succeeded" | "receipt_missing";
};

export type RecoveryPolicy = {
  "scope"?: "orders.upgrade_then_confirm/v1";
  "parent_version": string;
  "rules": Array<PolicyRule>;
};

export type ReductionAttempt = {
  "transform": string;
  "parent_hash": string;
  "child_hash": string;
  "trial_ids": Array<string>;
  "retained": boolean;
  "reason": string;
};

export type ReductionResult = {
  "schema_version"?: "faultlab/v1";
  "counterexample_id": string;
  "reducer_hash": string;
  "reduction_order": Array<string>;
  "original_recipe_hash": string;
  "retained_recipe_hash": (string | null);
  "attempts": Array<ReductionAttempt>;
  "status": "REDUCED" | "LOCALLY_MINIMAL" | "FLAKY" | "INCOMPLETE" | "NO_REDUCTION";
  "valid_count": number;
  "attempted_count": number;
  "target_violation_count": number;
  "stopping_reason": string;
  "neighborhood_exhausted": boolean;
};

export type RegressionBundle = {
  "export_version"?: "faultlab-regression/v1";
  "bundle_id": string;
  "manifest_hash": string;
  "files": Array<FileEntry>;
  "harness_version": string;
  "harness_hash": string;
  "source_recipe": FaultSpec;
  "retained_recipe": (FaultSpec | null);
  "fixture_id": "standard-v1" | "history-v1";
  "scope"?: "orders.upgrade_then_confirm/v1";
  "contract_hash": string;
  "capability_hash": string;
  "configuration_hash": string;
  "scorer_hash": string;
  "interpreter_hash": string;
  "policy_hash": string;
  "schema_hash": string;
  "dependency_lock_hash": string;
  "target_invariant": "C1" | "C2" | "C3" | "C4" | "C5" | "C6" | "C7" | "C8";
  "source_refs": Array<string>;
  "trial_results": Array<TrialResult>;
  "registration_requirements": Array<string>;
  "execution_profile_id": string;
  "caps": EpisodeBudget;
  "setup_instructions": string;
  "created_at"?: string;
};

export type RegressionCase = {
  "schema_version"?: "faultlab/v1";
  "regression_id": string;
  "campaign_id": string;
  "counterexample_id": string;
  "target_invariant": "C1" | "C2" | "C3" | "C4" | "C5" | "C6" | "C7" | "C8";
  "scope"?: "orders.upgrade_then_confirm/v1";
  "first_failing_policy": string;
  "accepted_policy": (string | null);
  "reduction_ref": (string | null);
  "diagnostic_ref": (string | null);
  "challenge_ref": (string | null);
  "bundle_id": (string | null);
};

export type RegressionExecution = {
  "schema_version"?: "faultlab/v1";
  "execution_id": string;
  "bundle_id": string;
  "manifest_hash": string;
  "registration_id": string;
  "profile_id": string;
  "mode": "VALIDATE_ONLY" | "RECORDED_PLAYBACK" | "FRESH_SANDBOX";
  "explicit_action": boolean;
  "policy_hash": string;
  "configuration_hash": string;
  "declared_budget": EpisodeBudget;
  "usage": Usage;
  "episode_ids": Array<string>;
  "world_ids": Array<string>;
  "status": "PENDING" | "RUNNING" | "COMPLETED" | "INCOMPLETE" | "REJECTED";
  "created_at"?: string;
  "stop_reason"?: (string | null);
};

export type ReportAction = {
  "kind": "report";
  "report": TaskReport;
};

export type SearchComparison = {
  "schema_version"?: "faultlab/v1";
  "comparison_id": string;
  "status": "PENDING" | "RUNNING" | "COMPLETED" | "INCOMPLETE";
  "campaign_id": string;
  "manifest_hash": string;
  "registration_id": string;
  "policy_hash": string;
  "generator_hash": string;
  "validator_hash": string;
  "deduplication_hash": string;
  "selector_order": Array<"explorer" | "systematic">;
  "systematic_digest": string;
  "context_ids": Array<string>;
  "trial_ids": Array<string>;
  "usage": Usage;
  "stopping_reason": string;
};

export type SendConfirmationAction = {
  "kind"?: "tool";
  "tool": "send_confirmation";
  "arguments": EmptyArguments;
};

export type ServiceStep = {
  "op": "retry_original_request" | "report_terminal_failure";
  "service": "orders" | "notifications";
  "only_if"?: "always" | "upgrade_receipt_missing" | "notification_receipt_missing" | "current_operation_pending" | "notification_operation_pending" | "upgrade_outcome_uncertain" | "notification_outcome_uncertain" | "upgrade_terminal_failure" | "notification_terminal_failure" | "upgrade_succeeded" | "notification_succeeded" | "receipt_missing";
};

export type StatusArguments = {
  "service": "orders" | "notifications";
};

export type TaskIntent = {
  "schema_version"?: "faultlab/v1";
  "task_id": string;
  "order_id": string;
  "desired_shipping"?: "express";
  "expected_version": number;
  "template_version"?: "confirmation/v1";
  "upgrade_operation_id": string;
  "notification_operation_id": string;
  "upgrade_idempotency_key": string;
  "notification_idempotency_key": string;
  "upgrade_intent_hash": string;
  "notification_intent_hash": string;
  "task_text": string;
};

export type TaskReport = {
  "upgrade_outcome": "NOT_STARTED" | "PENDING" | "SUCCEEDED" | "FAILED" | "UNKNOWN";
  "notification_outcome": "NOT_STARTED" | "PENDING" | "SUCCEEDED" | "FAILED" | "UNKNOWN" | "NOT_REQUIRED";
  "overall": "COMPLETED" | "SAFE_UNRESOLVED" | "CORRECTLY_REJECTED";
  "evidence_ids": Array<string>;
  "next_action": (NoNextAction | CheckNextAction);
};

export type TelemetryOutbox = {
  "schema_version"?: "faultlab/v1";
  "outbox_id": string;
  "payload_digest": string;
  "record_kind": "trace" | "evaluation" | "dataset" | "campaign";
  "record_ref": string;
  "state": "PENDING" | "UPLOADING" | "VERIFIED" | "ERROR";
  "attempts": number;
  "remote_ref": (string | null);
  "error_code": (string | null);
};

export type ToolCallRecord = {
  "schema_version"?: "faultlab/v1";
  "call_id": string;
  "episode_id": string;
  "tool": "get_order" | "update_order" | "get_operation_status" | "send_confirmation";
  "caller": "actor" | "policy";
  "hook": ("after_upgrade_response" | "before_confirmation" | "after_notification_response" | "before_final_report" | null);
  "attempt_ids": Array<string>;
  "observation_ids": Array<string>;
  "usage": Usage;
};

export type ToolResult = {
  "call_id": string;
  "tool": "get_order" | "update_order" | "get_operation_status" | "send_confirmation";
  "transport": "ok" | "timeout" | "error";
  "operation_id"?: (string | null);
  "order_id"?: (string | null);
  "status"?: ("PENDING" | "SUCCEEDED" | "FAILED" | "UNKNOWN" | null);
  "observed_version"?: (number | null);
  "receipt_id"?: (string | null);
  "retry_after_ticks"?: (number | null);
  "error_code"?: (string | null);
  "data"?: (Order | OperationData | null);
};

export type TrialResult = {
  "schema_version"?: "faultlab/v1";
  "episode_id": string;
  "world_id": string;
  "scenario_hash": string;
  "policy_hash": string;
  "arm": "B0" | "B1" | "L";
  "trial_index": number;
  "lifecycle": "COMPLETED" | "INTERRUPTED" | "LAB_ERROR";
  "outcome": ("COMPLETED" | "SAFE_UNRESOLVED" | "CORRECTLY_REJECTED" | "VIOLATION" | "LAB_ERROR" | null);
  "failed_checks"?: Array<"C1" | "C2" | "C3" | "C4" | "C5" | "C6" | "C7" | "C8">;
  "fault_scheduled": boolean;
  "fault_triggered": boolean;
  "usage"?: Usage;
  "reason"?: (string | null);
};

export type UpdateOrderAction = {
  "kind"?: "tool";
  "tool": "update_order";
  "arguments": UpgradeArguments;
};

export type UpgradeArguments = {
  "desired_shipping": "express";
};

export type Usage = {
  "http_attempts"?: number;
  "actor_calls"?: number;
  "model_calls"?: number;
  "input_tokens"?: number;
  "output_tokens"?: number;
  "wait_cycles"?: number;
  "ticks"?: number;
  "policy_steps"?: number;
  "wall_seconds"?: number;
  "cost_dollars"?: (number | null);
};

export type Verdict = {
  "schema_version"?: "faultlab/v1";
  "verdict_id": string;
  "episode_id": string;
  "outcome": "COMPLETED" | "SAFE_UNRESOLVED" | "CORRECTLY_REJECTED" | "VIOLATION" | "LAB_ERROR";
  "checks": Array<CheckResult>;
  "evidence_ids"?: Array<string>;
  "supported_completion": boolean;
  "useful_resolution": "completed" | "rejected" | "unresolved" | "invalid";
  "fault_executions"?: Array<FaultExecution>;
  "upgrade_effects": number;
  "notification_effects": number;
  "decision_tick": number;
  "horizon_tick": number;
  "scorer_hash": string;
};

export type WaitStep = {
  "op": "wait_ticks";
  "ticks": number;
  "only_if"?: "always" | "upgrade_receipt_missing" | "notification_receipt_missing" | "current_operation_pending" | "notification_operation_pending" | "upgrade_outcome_uncertain" | "notification_outcome_uncertain" | "upgrade_terminal_failure" | "notification_terminal_failure" | "upgrade_succeeded" | "notification_succeeded" | "receipt_missing";
};

export type WeaveIngestion = {
  "schema_version"?: "faultlab/v1";
  "ingestion_id": string;
  "episode_id": string;
  "source_project": string;
  "root_call_id": string;
  "origin": "prototype" | "faultlab_evaluation";
  "state": "PENDING" | "FETCHING" | "INGESTED" | "RETRYABLE_ERROR" | "REJECTED";
  "evidence_digest": (string | null);
  "execution_epoch": number;
  "reason": (string | null);
};

export type WorldSnapshot = {
  "schema_version"?: "faultlab/v1";
  "world_id": string;
  "tick": number;
  "orders": Array<Order>;
  "operations": Array<Operation>;
  "notifications": Array<NotificationEffect>;
  "events": Array<Event>;
};
