"""Generate TypeScript declarations from the canonical Pydantic JSON schemas."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
schemas={}
for path in sorted((ROOT/'contracts').glob('*.schema.json')):
    schema=json.loads(path.read_text())
    schemas.update(schema.get('$defs',{}))
    schemas[path.name.removesuffix('.schema.json')]=schema


def typ(s):
    if '$ref' in s: return s['$ref'].split('/')[-1]
    if 'const' in s: return json.dumps(s['const'])
    if 'enum' in s: return ' | '.join(json.dumps(v) for v in s['enum'])
    for key in ('anyOf','oneOf'):
        if key in s:return '('+' | '.join(typ(x) for x in s[key])+')'
    t=s.get('type')
    if t=='string':return 'string'
    if t in ('number','integer'):return 'number'
    if t=='boolean':return 'boolean'
    if t=='null':return 'null'
    if t=='array':
        if 'prefixItems' in s:return '['+', '.join(typ(x) for x in s['prefixItems'])+']'
        return f'Array<{typ(s.get("items",{}))}>'
    if t=='object':
        props=s.get('properties',{})
        if not props:return 'Record<string, unknown>' if s.get('additionalProperties',True) else 'Record<string, never>'
        required=s.get('required',[])
        return '{\n'+''.join(f'  {json.dumps(k)}{"" if k in required else "?"}: {typ(v)};\n' for k,v in props.items())+'}'
    return 'unknown'

text='// Generated by scripts/export-wire-types.py from contracts/*.schema.json.\n'
text+='// JSON wire data only; validate responses before using them.\n\n'
for name,schema in sorted(schemas.items()):text+=f'export type {name} = {typ(schema)};\n\n'
(ROOT/'contracts/wire-types.ts').write_text(text.rstrip()+'\n')
